# Assignment 13: Lambda and Keyword Arguments #

### Goals for this Assignment ###

By the time you have completed this assignment, you should be able to:

- Use `lambda` to create new functions in any position an expression is expected
- Use the `key` keyword argument of `sorted` to help sort a list of custom objects
- Define a function using keyword and optional arguments

## Step 1: Use `lambda` to Create Functions ##

### Background: `lambda` and Abstracting Over Computation ###

By this point, you are used to defining your own functions.
However, it turns out there is a bit of a limit to the sorts of functions we have been working with.
To illustrate this, let's revisit the pseudocode shown in step 1 of assignment 11, duplicated below for convenience:

```python
new_variable = initial_value
for element in some_list:
    new_variable = some_operation(new_variable, element)
```

In assignment 11, it was stated that this sort of pattern comes up frequently in code, and is used to incrementally build up a result while iterating over some list.
Some of your solutions for assignment 11 required you to repeat this pattern in order to solve various problems.
However, this begs a question: why repeat this code, when we could instead _abstract_ over this code by defining a function?
That is, why didn't we just define a function that executed the code shown above, and then merely call that function each time we needed that code, instead of repeating the code itself?

Towards that end, we will try to define a function which abstracts over the above pattern.
The usual strategy when abstracting over code in this fashion is that anything that is expected to be different in different problem instances becomes a variable.
In the code above, `initial_value`, `some_list`, and `some_operation` all depend on the specific instance of the problem (i.e., the thing we are actually trying to compute), and therefore these make sense to turn into function parameters.
We attempt to do this in the next cell.

In [1]:
def pattern(initial_value, some_list, some_operation):
    new_variable = initial_value
    for element in some_list:
        new_variable = some_operation(new_variable, element)
    return new_variable

The code above is a valid Python function.
`initial_value`, `some_list`, and `some_operation` all became parameters, and therefore someone using `pattern` could pass in different values for there parameters.
`new_variable` becomes a local variable in `pattern`, i.e., `new_variable` is only in scope within the `pattern` function.
`element` similarly is in scope within the `for...in` loop, and the body of the loop repeatedly updates `new_variable`.
The part that may potentially jump out at you as strange is the `some_operation(new_variable, element)` part.
This shows us _calling_ `some_operation` as a function, passing `new_variable` and `element` as parameters.
Keep in mind that `some_operation` here is a _parameter_ to `pattern`, and therefore the value of `some_operation` depends on the specific call to `pattern`.
In the above code, `some_operation` will be called as many times as there are elements in `some_list`.

For the above code to work, we need to be able to pass functions themselves as parameters to other functions.
Or, phrased another way, this code assumes we can treat functions as data, meaning we can assign functions to variables and treat them as we do any other data (e.g, integers, strings, etc.).

It turns out that Python does allow this, and `pattern` already is correctly written to use a function as a parameter.
The question now is how to pass in a function as a value into `pattern`.
This can be most directly done in Python via use of `lamdba` expressions, which create new functions on the fly.
Specifically, a `lambda` expression will create an object of type `function`, and `function` objects can be called.
This is shown by example in the cell below.

In [2]:
add = lambda a, b: a + b
increment = lambda x: x + 1
mult = lambda first, second: first * second

print(add(1, 2)) # prints 3
print(add(5, 6)) # prints 11

print(increment(0)) # prints 1
print(increment(2)) # prints 3

print(mult(4, 2)) # prints 8
print(mult(8, 4)) # prints 32

3
11
1
3
8
32


To provide some explanation to the above code, let's elaborate on the first line.
The expression `lambda a, b: a + b` creates a `function` object.
The specific function takes two parameters; here we specify the formal parameters, which are named `a` and `b`, respectively.
When called, `a` and `b` will be bound to the two actual parameters, and the function will evaluate `a + b` and return whatever `a + b` returns.
From there, we bind a reference to this newly-created function object to the `add` variable.
Later on, when we call this function (e.g., with `add(1, 2)`), this references the `add` variable, and calls this `function` object.

The next two lines show that `lambda` functions work much like normal functions: they can take any number of parameters, and the names of the formal parameters have the same rules as named for the formal paramerters of more typical, named functions.

Using `pattern` and `lambda`, we can revisit the `product` function from assignment 11, which is repeated in the next cell for convenience:

In [3]:
def product(numbers):
    result = 1
    for number in numbers:
        result = result * number
    return result

We can redefine `product` with a call to `pattern` with `lambda`, shown below:

In [4]:
def new_product(numbers):
    return pattern(1, numbers, lambda a, b: a * b)

print(new_product([2, 5])) # prints 10
print(new_product([1, 8, 2])) # prints 16
print(new_product([4, 5, 3, 2])) # prints 120
print(new_product([])) # prints 1

10
16
120
1


### Try this Yourself ###

Consider the `print` statements and comments below, which make calls to various functions with various behaviors.
Define these functions using `lambda` and variables with the appropriate names, similar to what was done with `add`, `increment`, and `mult` above.

In [5]:
# Define your functions USING LAMBDA here.  Leave the calls below for testing.
decrement = lambda x: x - 1
div = lambda first, second: first / second
exponent = lambda first, second: first**second

print(decrement(5)) # should print 4
print(decrement(2)) # should print 1

print(div(4, 2)) # should print 2.0
print(div(7, 2)) # should print 3.5

print(exponent(2, 2)) # should print 4
print(exponent(2, 3)) # should print 8
print(exponent(3, 2)) # should print 9
print(exponent(4, 2)) # should print 16

4
1
2.0
3.5
4
8
9
16


## Step 2: Print Only Specified Elements of a List ##

For this step, you'll need to define a function with the following constraints:

- The name of the function is `print_some`
- `print_some`'s first parameter is a list of elements of any type
- `print_some`'s second parameter is a function, which takes a single parameter.  The function should be able to take any kind of element in the list.  The function returns a Boolean indicating if a given list element should be printed or not.
- `print_some` itself should be defined as a typical named function with `def`, but it is expected to take a function, much like `pattern` above.

Example calls to `print_some` are shown in the next cell, along with the expected output.
Define `print_some` in the next cell.
Leave the calls in place in order to test your code.

In [9]:
# Define your function below.  Leave the calls in place to test your code.
print_some = lambda li, func:[print(item) for item in li if func(item)]

print_some([3, 2, 8, 5, 4], lambda x: x % 2 == 0)
# the above statement prints all even elements of the given list, namely:
# 2
# 8
# 4

print()
print_some([3, 2, 8, 5, 4], lambda x: x % 2 == 1)
# the above statement prints all odd elements of the given list, namely:
# 3
# 5

print()
print_some([8, 2, 4, 9, 0], lambda x: x <= 4)
# the above statement prints all elements <= 4, namely:
# 2
# 4
# 0

print()
print_some([8, 2, 4, 9, 0], lambda x: x > 5)
# the above statement prints all elements > 5, namely:
# 8
# 9

2
8
4

3
5

2
4
0

8
9


[None, None]

## Step 3: Utilize the `key` Parameter of `sorted` to Sort a List of Objects ##

### Background: Sorting Lists in Python and Keyword Arguments ###

There exist a large variety of [_sorting algorithms_](https://en.wikipedia.org/wiki/Sorting_algorithm), which are general approaches to putting the elements of a list in sorted order (e.g., `[1, 2, 3]`, vs. `[3, 1, 2]`).
Exactly how these algorithms work and why there are so many of them is beyond the scope of this course.
For our purposes, you need only know that Python already provides a way to sort lists out of the box, namely with the `sorted` function and the `sort` method.
A description of both follow.

`sorted` is a built-in function which takes a list and returns a new, sorted version of that list.
This is illustrated in the cell below.

In [10]:
first_list = [9, 3, 7, 2]
second_list = sorted(first_list)
print(first_list) # prints [9, 3, 7, 2]
print(second_list) # prints [2, 3, 7, 9]

[9, 3, 7, 2]
[2, 3, 7, 9]


As shown, the call to `sorted` does not change `first_list`, and instead returns a new list of the same elements but in sorted order.

In constrast, the closely-related `sort` method on lists _does_ modify the original list.
This is shown by example in the cell below:

In [11]:
some_list = [3, 2, 8, 5, 0, 1]
some_list.sort()
print(some_list) # prints [0, 1, 2, 3, 5, 8]

[0, 1, 2, 3, 5, 8]


As short, `sort` modifies the list itself; this is sometimes referred to as modifying the list in-place.
Because `sort` does not create a new list, this can be better for minimizing memory usage.
However, in some contexts `sorted` is much more convenient, and the extra memory usage is moot if one needs to make a copy of the original list anyway for some reason.

`sorted` can be applied to lists holding any elements.
For example, we can also use `sorted` to sort lists of strings, which will put them in [lexicographic ordering](https://en.wikipedia.org/wiki/Lexicographic_order) (i.e., as you'd see the words in a dictionary).
This is shown in the next cell.

In [12]:
third_list = ["foo", "bar", "baz", "blah", "moo", "cow", "bull"]
fourth_list = sorted(third_list)
print(third_list) # prints ['foo', 'bar', 'baz', 'blah', 'moo', 'cow', 'bull']
print(fourth_list) # prints ['bar', 'baz', 'blah', 'bull', 'cow', 'foo', 'moo']

['foo', 'bar', 'baz', 'blah', 'moo', 'cow', 'bull']
['bar', 'baz', 'blah', 'bull', 'cow', 'foo', 'moo']


Internally, `sorted` needs to know how to compare any two individual elements of a list to each other, in order to know which element is supposed to come before which other element.
`sorted` achieves this with `<`, which works over both integers and strings, like so:

In [13]:
print(1 < 2)
print(2 < 1)
print("foo" < "bar")
print("bar" < "foo")

True
False
False
True


The one problem with using `<` is that it only works if all objects in the list have the same type.
For example, if you try:

In [14]:
print(sorted(["foo", 1, 2, "bar"]))

TypeError: '<' not supported between instances of 'int' and 'str'

...this ends up crashing with a `TypeError` stating that you can't compare an `int` to a `str`.

On some level, this error makes sense: what does it mean for an integer to be less than some given string?
In general, there might not be an answer to this question.
But for your specific application, there might be.
For example, one way to circumvent this issue would be to use the string representation (from the `str` function) of each integer involved, in order to uniformly compare strings.
In other words, we instead do:

In [15]:
print(sorted(["foo", "1", "2", "bar"]))

['1', '2', 'bar', 'foo']


The above code gives us `['1', '2', 'bar', 'foo']`, putting the numbers before the strings.
This, admittedly, is not always desirable, and can have some unintended consequences.
For example, multi-digit integers exhibit some potentially surprising behavior:

In [16]:
print(sorted(["foo", "1", "2", "bar", "12", "123", "133"]))

['1', '12', '123', '133', '2', 'bar', 'foo']


If the above cell is run, you'll see that `'2'` is listed after all the other numbers.
The reasoning is because we aren't comparing these as numbers anymore, but rather as strings, and the character `2` on the keyboard comes after `1`.
Per dictionary ordering, this means that any number that starts with `1` must come before any number starting with `2`.
For our purposes, we will say this is intended behavior, but in general, this might not be what you want.

While we can now sort numbers along with our strings, we needed to change the list elements themselves to do this.
This might be desirable, but for our purposes, let's assume it isn't.
We instead want our original list elements, intermixed with strings and integers, but in sorted order based on the string representation of all the elements.
In other words, we want the output list `[1, 12, 123, 133, 2, 'bar', 'foo']`, _not_ `['1', '12', '123', '133', '2', 'bar', 'foo']` (i.e., the integers should be integers, not strings of digits).

It turns out the `sorted` function does have a way to do exactly what we want, by passing an additional parameter.
Specifically, we can pass a function to `sorted`, and the function will be called on every element of the original list.
The list items will be sorted _by the output of the function_, as opposed to sorting the items themselves.
This is best shown by example, seen in the following cell:

In [17]:
print(sorted(["foo", 1, 2, "bar", 12, 123, 133], key=lambda e: str(e)))

[1, 12, 123, 133, 2, 'bar', 'foo']


If the above cell is run, you'll see that you get an output list containing both strings and integers.
`sorted` has been given an additional parameter, namely the whole `key=lambda e: str(e)` part.
The `key=` part is referred to as a _keyword argument_ in Python, that is, we can pass parameters with specific names.
These names are fixed by the function itself; i.e., `sorted` here is specifically defined to take a keyword argument named `key`.
In many cases, keyword arguments are _optional_, meaning they don't have to be passed (and we were not passing them with all the prior calls to `sorted`).
The `lambda e: str(e)` part creates a function which takes a single parameter (named `e`), and will return the result of `str(e)`.
That is, this function returns the string representation of its argument.
In thise case, the actual sort performed by `sorted` is then performed on those string representations, though the original elements are nonetheless preserved.

The `sort` method also takes a `key` parameter, and uses this in the same way as `sorted` does.
For example:

In [18]:
original_items = ["foo", 1, 2, "bar", 12, 123, 133]
original_items.sort(key=lambda e: str(e))
print(original_items)

[1, 12, 123, 133, 2, 'bar', 'foo']


### Try This Yourself ###

In the next cell, a custom class is defined which will internally hold an integer (named `some_integer`).
The goal is to sort instances of this class (i.e., objects) based on the value of `some_integer`.
You can achieve this goal via the use if `key=`, provided a `lambda` function.
The provided calls to `sorted` will currently not work correctly without this additional keyword argument.
Modify the calls to `sorted` to add `key=` arguments which will lead to the correct output.

In [21]:
class CustomClass:
    def __init__(self, some_integer):
        self.some_integer = some_integer

one = CustomClass(1)
two = CustomClass(2)
three = CustomClass(3)
four = CustomClass(4)
items = [four, one, three, two]

sorted_items = sorted(items, key=lambda e: e.some_integer) # modify this line to add a key= parameter

for item in sorted_items:
    print(item.some_integer)

# Overall expected output:
# 1
# 2
# 3
# 4

1
2
3
4


## Step 4: Define a Function with an Optional Keyword Argument ##

### Background: Defining Functions with Keyword Arguments ###

Up until this point, you've only defined functions which take positional arguments.
For example, with:

In [22]:
def add(x, y):
    return x + y

...`x` is in the first position, and `y` is in the second position.
This means that in the call `add(5, 6)`, since `5` is in the first position in the call, `x` will be bound to `5`.
Similarly, since `6` is in the second position in the call, `y` will be bound to `6`.

It turns out that Python also allows us to specify `x` and `y` as keyword arguments here, as with the call:

In [23]:
# Be sure to load prior cell defining add before this one, or else this one
# won't have the `add` function defined
print(add(x=3, y=4))

7


As shown, you can use the names of the formal parameters as keyword arguments, and everything works as normal.
In fact, when one calls a function using keyword arguments in this style, there is no need to maintain the position of those arguments.
For example:

In [24]:
print(add(y=5, x=1))

6


As shown, even though positionally `x` is defined before `y` in the `add` function, we can nonetheless pass `y` first, as long as we are using keyword arguments.
Rewritten as positional arguments, the above call is equivalent to `add(1, 5)`.

### Background: Optional Arguments and Default Arguments ###

`sort` and `sorted` both took the keyword argument `key`, but you don't have to provide `key`.
For this reason, `key` is said to be optional.
One can define functions which take optional parameters by providing a value which will be used by default if the caller does not provide such a value.
This is most easily shown by example, like so:

In [25]:
def increment(value, by=1):
    return value + by

print(increment(3))
print(increment(4, by=2))

4
6


As shown, `increment` takes a positional argument `value`, which must be provided.
However, the second parameter `by` looks a little weird, because it ends with `=1`.
The `=` part says that `by` has a _default_ value, namely `1` in this case.
Semantically, if the caller provides a value for `by`, then whatever value passed is used.
For example, in the above cell with `increment(4, by=2)`, because a value for `by` is explicitly passed, the value of `by` will be `2` inside of the `increment` function.
However, with the call `increment(3)`, no value for `by` was passed.
As a result, `by` will instead use the default value in `increment`'s definition, so `by` will be `1`.

### Try this Yourself ###

Define a function named `decrement`, which works much like the `increment` function above, but it will instead subtract the given optional value `by` from the given number.
Example calls are shown in the next cell, along with comments showing what those calls should return.
Leave the calls in place in order to test your code.

In [27]:
# Define your function here.  Leave the calls below for testing purposes.
def decrement(value, by=1):
    return value - by

print(decrement(3)) # should print 2
print(decrement(4, by=2)) # should print 2
print(decrement(5, by=4)) # should print 1

2
2
1


## Step 5: Define a Function Which Returns a Possibly-Transformed List ##

Define a function with the following constraints:

- The name of the function is `maybe_transform`
- `maybe_transform` takes a list of elements
- `maybe_transform` takes an optional function, with the named argument `using`
- `maybe_transform` returns a new list

If the optional function is provided, `maybe_transform` will return a new list holding the results of applying the function to each element of the original list.
If the optional function is not provided, `maybe_transform` will return a new list which is a copy of the original list.

Example calls are shown in the next cell, along with comments showing what those calls should return.
Leave the calls in place in order to test your code.
As a hint, list comprehensions may be useful here, and you can define a `lambda` which just returns its parameter.

In [29]:
# Define your function here.  Leave the calls below for testing purposes.
maybe_transform = lambda elements, using=None: [using(item) if using else item for item in elements]


print(maybe_transform([3, 2, 9, 4], using=lambda x: x + 1)) # should print [4, 3, 10, 5]
print(maybe_transform(["foo", "bar", "blah"], using=lambda s: len(s))) # should print [3, 3, 4]
print(maybe_transform([True, False, False])) # should print [True, False, False]

[4, 3, 10, 5]
[3, 3, 4]
[True, False, False]


## Step 6: Submit via Canvas ##

Be sure to **save your work**, then log into [Canvas](https://canvas.csun.edu/).  Go to the COMP 502 course, and click "Assignments" on the left pane.  From there, click "Assignment 13".  From there, you can upload the `13_lambda_keyword_arguments.ipynb` file.

You can turn in the assignment multiple times, but only the last version you submitted will be graded.